@tag update.

diff --git a/modules/Git/clone b/modules/Git/clone
--- a/modules/Git/clone
+++ b/modules/Git/clone
@@ -47,15 +47,17 @@ declare tag
 	git clone -b ${branch} ${respo} "${target}"
 
 	switch_dir_to "${target}"
-	@log "Git tags: $(git tag -l)"
+	@log "Git tags:\n \"$(git tag -l)\""
 
-	if [[ -n $tag ]]; then
-		@log "Should checkout tag : $tag"
-	fi
 	if [[ "$tag" != "" && `git tag -l $tag` == $tag ]]; then
 		@log "Checkout tag: $tag..."
 		git checkout tags/$tag
-		@log "Checkout succeed."
+		if [[ $? == 0 ]]; then
+			@log "Checkout tag/$tag succeed."
+		else
+			@log "Checkout tag/$tag failed."
+		fi
+
 	fi
 	restore_dir
 
